// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function Button(Props) {
  var onClick = Props.onClick;
  var children = Props.children;
  var tmp = {
    className: "rounded-md group bg-blue text-white inline-block h-8 px-3"
  };
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement("button", tmp, children);
}

var make = Button;

exports.make = make;
/* react Not a pure module */
