// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

function Link(Props) {
  var className = Props.className;
  var href = Props.href;
  var children = Props.children;
  var onClick = function (evt) {
    evt.preventDefault();
    return ReasonReactRouter.push(href);
  };
  var tmp = {
    href: href,
    onClick: onClick
  };
  if (className !== undefined) {
    tmp.className = Caml_option.valFromOption(className);
  }
  return React.createElement("a", tmp, children);
}

var make = Link;

exports.make = make;
/* react Not a pure module */
