// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Icon = require("../common/Icon.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function shorten(address) {
  var length = address.length;
  if (length < 20) {
    return address;
  }
  var firstPart = address.substr(0, 8);
  var lastPart = address.substr(length - 8 | 0);
  return firstPart + ("..." + lastPart);
}

function TzAddress(Props) {
  var versionOpt = Props.version;
  var address = Props.address;
  var version = versionOpt !== undefined ? versionOpt : /* Short */1;
  var str = version ? shorten(address) : address;
  var title = version ? address : undefined;
  var tmp = {
    className: "flex items-center text-grey-40 font-bold text-10"
  };
  if (title !== undefined) {
    tmp.title = Caml_option.valFromOption(title);
  }
  return React.createElement("span", tmp, React.createElement("button", {
                  className: "inline mr-2"
                }, React.createElement(Icon.Copy.make, {
                      className: "w-3 h-3"
                    })), str);
}

var make = TzAddress;

exports.shorten = shorten;
exports.make = make;
/* Icon Not a pure module */
