// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Electron = require("electron");

var IpcRenderer = {};

var IpcMain = {};

Electron.ipcRenderer.handle("perform-action", (function (evt, arg) {
        console.log("event", evt);
        console.log("arg", arg);
        
      }));

exports.IpcRenderer = IpcRenderer;
exports.IpcMain = IpcMain;
/*  Not a pure module */
