// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Route = require("./Route.js");
var React = require("react");
var Page404 = require("../pages/Page404.js");
var Sidebar = require("../components/Sidebar.js");
var Dashboard = require("../pages/Dashboard.js");
var TransactionsPage = require("../pages/TransactionsPage.js");
var ReactHotLoader = require("react-hot-loader");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");

var HotReloader = {};

var current = {
  name: "Private Wallet",
  address: "tz1fvLppfweTwyfrW7WuqKVicVJkWB7bJV6y"
};

var mockupState_wallets = [
  current,
  {
    name: "Business Wallet",
    address: "tz1bDXD6nNSrebqmAnnKKwnX1QdePSMCj4MX"
  }
];

var mockupState = {
  wallets: mockupState_wallets,
  current: current
};

function App(Props) {
  var url = ReasonReactRouter.useUrl(undefined, undefined);
  var route = Route.fromUrl(url);
  var match = React.useState(function () {
        return mockupState;
      });
  var setState = match[1];
  var state = match[0];
  React.useEffect((function () {
          var watchId = ReasonReactRouter.watchUrl(function (url) {
                console.log("Route switched to", url);
                
              });
          return (function (param) {
                    return ReasonReactRouter.unwatchUrl(watchId);
                  });
        }), []);
  var content;
  switch (route) {
    case /* Dashboard */0 :
        content = React.createElement(Dashboard.make, {
              wallet: state.current
            });
        break;
    case /* Transactions */1 :
        content = React.createElement(TransactionsPage.make, {
              wallet: state.current
            });
        break;
    case /* Page404 */2 :
        content = React.createElement(Page404.make, {});
        break;
    
  }
  var onWalletSelect = function (wallet) {
    console.log("selected wallet: ", wallet);
    return Curry._1(setState, (function (prev) {
                  return {
                          wallets: prev.wallets,
                          current: wallet
                        };
                }));
  };
  return React.createElement("div", {
              className: "flex"
            }, React.createElement("div", undefined, React.createElement(Sidebar.make, {
                      wallets: state.wallets,
                      onWalletSelect: onWalletSelect
                    })), content);
}

var make = ReactHotLoader.hot(module)(App);

var mockup_address2 = "tz1bDXD6nNSrebqmAnnKKwnX1QdePSMCj4MX";

var mockup_address = "tz1fvLppfweTwyfrW7WuqKVicVJkWB7bJV6y";

exports.HotReloader = HotReloader;
exports.mockup_address2 = mockup_address2;
exports.mockup_address = mockup_address;
exports.mockupState = mockupState;
exports.make = make;
/* make Not a pure module */
