// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Icon$Clipboard(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("path", {
                  d: "M16 4h2a2 2 0 012 2v14a2 2 0 01-2 2H6a2 2 0 01-2-2V6a2 2 0 012-2h2"
                }), React.createElement("rect", {
                  height: "4",
                  width: "8",
                  rx: "1",
                  ry: "1",
                  x: "8",
                  y: "2"
                }));
}

var Clipboard = {
  make: Icon$Clipboard
};

function Icon$ArrowUp(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("path", {
                  d: "M12 19V5M5 12l7-7 7 7"
                }));
}

var ArrowUp = {
  make: Icon$ArrowUp
};

function Icon$ArrowDown(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("path", {
                  d: "M12 5v14M19 12l-7 7-7-7"
                }));
}

var ArrowDown = {
  make: Icon$ArrowDown
};

function Icon$UpCircle(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("circle", {
                  cx: "12",
                  cy: "12",
                  r: "10"
                }), React.createElement("path", {
                  d: "M16 12l-4-4-4 4M12 16V8"
                }));
}

var UpCircle = {
  make: Icon$UpCircle
};

function Icon$UpDownArrow(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              height: "10",
              width: "18",
              fill: "none",
              viewBox: "0 0 18 10"
            }, React.createElement("path", {
                  className: "stroke-current " + className,
                  d: "M4.203 8.595V1.688M.75 5.141l3.453-3.453 3.454 3.453M13.796 1.688v6.907M17.25 5.141l-3.454 3.454-3.453-3.454",
                  strokeLinecap: "round",
                  strokeLinejoin: "round",
                  strokeWidth: "1.5"
                }));
}

var UpDownArrow = {
  make: Icon$UpDownArrow
};

function Icon$Plus(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current" + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("path", {
                  d: "M12 5v14M5 12h14"
                }));
}

var Plus = {
  make: Icon$Plus
};

function Icon$Copy(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("rect", {
                  height: "13",
                  width: "13",
                  rx: "2",
                  ry: "2",
                  x: "9",
                  y: "9"
                }), React.createElement("path", {
                  d: "M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"
                }));
}

var Copy = {
  make: Icon$Copy
};

function Icon$Burger(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("path", {
                  d: "M3 12h18M3 6h18M3 18h18"
                }));
}

var Burger = {
  make: Icon$Burger
};

function Icon$VerticalDots(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "stroke-current " + className,
              height: "24",
              width: "24",
              fill: "none",
              stroke: "currentColor",
              strokeLinecap: "round",
              strokeLinejoin: "round",
              strokeWidth: "2",
              viewBox: "0 0 24 24"
            }, React.createElement("circle", {
                  cx: "12",
                  cy: "12",
                  r: "1"
                }), React.createElement("circle", {
                  cx: "12",
                  cy: "5",
                  r: "1"
                }), React.createElement("circle", {
                  cx: "12",
                  cy: "19",
                  r: "1"
                }));
}

var VerticalDots = {
  make: Icon$VerticalDots
};

function Icon$Wallet(Props) {
  var classNameOpt = Props.className;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("svg", {
              className: "fill-current " + className,
              height: "512",
              width: "512",
              viewBox: "0 0 512.007 512.007"
            }, React.createElement("path", {
                  d: "M466.004 176.007h-82V36.033c0-12.568-6.383-24.016-17.074-30.624-10.689-6.607-23.783-7.197-35.025-1.576a17.33 17.33 0 00-.428.222L34.697 163.777a65.863 65.863 0 00-34.693 58.07v244.16c0 25.364 20.636 46 46 46h420c25.364 0 46-20.636 46-46v-244c0-25.364-20.636-46-46-46zM346.355 32.388c1.587-.73 2.911-.276 3.751.243.866.535 1.897 1.56 1.897 3.403v139.974H79.496zm133.649 433.619c0 7.72-6.28 14-14 14h-420c-7.72 0-14-6.28-14-14v-244c0-7.72 6.28-14 14-14h420c7.72 0 14 6.28 14 14z"
                }), React.createElement("path", {
                  d: "M416.004 376.007c-17.645 0-32-14.355-32-32s14.355-32 32-32 32 14.355 32 32-14.356 32-32 32zm0-32l.001.021z"
                }));
}

var Wallet = {
  make: Icon$Wallet
};

exports.Clipboard = Clipboard;
exports.ArrowUp = ArrowUp;
exports.ArrowDown = ArrowDown;
exports.UpCircle = UpCircle;
exports.UpDownArrow = UpDownArrow;
exports.Plus = Plus;
exports.Copy = Copy;
exports.Burger = Burger;
exports.VerticalDots = VerticalDots;
exports.Wallet = Wallet;
/* react Not a pure module */
