// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function toString(t) {
  if (t) {
    return "testnet";
  } else {
    return "mainnet";
  }
}

exports.toString = toString;
/* No side effect */
